name: "Continuous Integration"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for plugin gradlew
        run: chmod +x ./localization-plugin/gradlew
      - name: Grant execute permission for consumer gradlew
        run: chmod +x ./test-consumer/gradlew
      - name: Build Localization Plugin
        run: ./localization-plugin/gradlew build jar -b ./localization-plugin/build.gradle.kts
      - name: Build Consumer
        run: ./test-consumer/gradlew build -b ./test-consumer/build.gradle.kts
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: jar
          path: ./localization-plugin/build/libs/*.jar
